blank_issues_enabled: false
contact_links:
  - name: GitHub
    url: https://github.com/ViratiAkiraNandhanReddy
    about: "Reach out to us on GitHub"
  - name: Latest Gist
    url: https://gist.github.com/ViratiAkiraNandhanReddy
    about: "Check out our latest Gists"
  - name: Website
    url: https://viratiakiranandhanreddy.github.io/
    about: "Visit our Website"
  - name: Instagram
    url: https://instagram.com/viratiaki53
    about: "Follow us on Instagram"
  - name: LinkedIn
    url: https://www.linkedin.com/in/viratiakiranandhanreddy
    about: "Connect with us on LinkedIn"
  - name: X (Twitter)
    url: https://x.com/Viratiaki53
    about: "Follow us on X (Twitter)"
  - name: Facebook
    url: https://facebook.com/ViratiAkiraNandhanReddy
    about: "Like us on Facebook"
  - name: YouTube
    url: https://youtube.com/@ViratiAkiraNandhanReddy
    about: "Subscribe to us on YouTube"
  - name: Python Package Index (PyPI)
    url: https://pypi.org/user/ViratiAkiraNandhanReddy
    about: "Check out our projects on PyPI"