name: '📉 : PERFORMANCE ISSUE'
description: Report slowness, lag, or performance degradation in the project.
title: "[Performance]: <Short description here>"
labels: ["help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Performance Issue Report
        Thank you for taking the time to report a performance problem!  
        Please fill out the sections below to help us reproduce and fix it efficiently.  
        ---

  - type: input
    id: summary
    attributes:
      label: '📝 : SUMMARY'
      description: Briefly describe the performance problem.
      placeholder: "e.g., App becomes slow when loading large datasets"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '💬 : DETAILED DESCRIPTION'
      description: Describe when and how the performance issue occurs.
      placeholder: |
        Please explain in detail:
        - What specific action or area is slow?
        - What are you expecting instead?
        - How much slower is it compared to before?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: '🔁 : STEPS TO REPRODUCE'
      description: Provide a clear step-by-step way to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Perform '...'
        3. Observe slowdown at '...'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: '🧩 : ENVIRONMENT DETAILS'
      description: Add environment and system details for better context.
      placeholder: |
        - OS: Windows 11 / Ubuntu 22.04 / macOS Sonoma
        - Browser or Runtime: Chrome 130 / Node.js 20 / Python 3.12
        - Hardware: CPU, RAM
        - App Version or Commit Hash: v1.2.3 / a1b2c3d
    validations:
      required: true

  - type: textarea
    id: performance_metrics
    attributes:
      label: '📊 : PERFORMANCE METRICS / BENCHMARKS (IF AVAILABLE)'
      description: Include measurements, logs, or screenshots that show the slowdown.
      placeholder: |
        - Before: 200ms load time  
        - After: 3.5s load time  
        - CPU usage: 85%  
        - Memory usage: 2GB  
        - Logs or profiler output:
          ```
          [timestamp] Heavy computation in main thread...
          ```
    validations:
      required: false

  - type: textarea
    id: possible_cause
    attributes:
      label: '🔍 : POSSIBLE CAUSE (OPTIONAL)'
      description: If you have an idea of what’s causing the issue, mention it here.
      placeholder: "Maybe due to inefficient loop / database query / rendering bottleneck"
    validations:
      required: false

  - type: textarea
    id: suggestions
    attributes:
      label: '💡 : SUGGESTED IMPROVEMENTS (OPTIONAL)'
      description: Suggest any potential optimization or fix.
      placeholder: "Perhaps cache this data / use lazy loading / reduce re-renders"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        🧠 **Tip:**  
        You can attach performance profiler data, screenshots, or short screen recordings to help us investigate faster.

        🙏 Thank you for helping us keep the project efficient and fast!